# Generated by Django 2.2.3 on 2021-01-09 18:18

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Booking',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('dateofbooking', models.CharField(max_length=50, verbose_name='date of booking')),
                ('timeofbooking', models.DateTimeField(verbose_name='time of booking')),
                ('typebooking', models.CharField(max_length=50, verbose_name='type booking')),
                ('numberbooking', models.PositiveIntegerField(verbose_name='number booking')),
                ('accountnumber', models.CharField(max_length=50, verbose_name='account number')),
                ('idclient', models.PositiveIntegerField(verbose_name='id client')),
            ],
        ),
    ]
