# Generated by Django 2.2.3 on 2021-01-10 12:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_auto_20210110_1143'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bookinginvoice',
            name='price',
            field=models.CharField(max_length=50, verbose_name='type of place'),
        ),
    ]
