# Generated by Django 2.2.3 on 2021-01-10 08:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Bookinginvoice',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numberbooking', models.PositiveIntegerField(verbose_name='number booking')),
                ('dateofbooking', models.DateTimeField(verbose_name='date of booking')),
                ('typeofplace', models.CharField(max_length=50, verbose_name='type of place')),
                ('price', models.PositiveIntegerField(verbose_name='price')),
            ],
        ),
        migrations.CreateModel(
            name='Places',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('typeofplace', models.CharField(max_length=50, verbose_name='type of place')),
            ],
        ),
        migrations.CreateModel(
            name='ProvisionOfOtherServices',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('typeofservice', models.CharField(max_length=50, verbose_name='type of place')),
                ('priceoftheservice', models.PositiveIntegerField(verbose_name='priceoftheservice')),
                ('accountnumber', models.PositiveIntegerField(verbose_name='accountnumber')),
            ],
        ),
        migrations.CreateModel(
            name='Room',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('typeofrooms', models.CharField(max_length=50, verbose_name='type of rooms')),
                ('numberofseats', models.PositiveIntegerField(verbose_name='number of seats')),
                ('numberofrooms', models.PositiveIntegerField(verbose_name='number of rooms')),
            ],
        ),
        migrations.CreateModel(
            name='Theclient',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('Nameorfullnameoftheindividual', models.CharField(max_length=50, verbose_name='Name or fullname of the individual')),
                ('Thepassportseries', models.CharField(max_length=50, verbose_name='the passport series')),
                ('numberbooking', models.PositiveIntegerField(verbose_name='number booking')),
                ('accountnumber', models.PositiveIntegerField(verbose_name='account number')),
            ],
        ),
        migrations.CreateModel(
            name='TypeOfPlaces',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('price', models.PositiveIntegerField(verbose_name='price')),
                ('nametypeofplace', models.CharField(max_length=50, verbose_name='name type of place')),
            ],
        ),
        migrations.CreateModel(
            name='TypeOfRooms',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('price', models.PositiveIntegerField(verbose_name='price')),
                ('nametypeofroom', models.CharField(max_length=50, verbose_name='name type of room')),
            ],
        ),
        migrations.CreateModel(
            name='TypeOfService',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('NameOfTheServicetype', models.CharField(max_length=50, verbose_name='type of place')),
                ('CurrentCostOfTheService', models.PositiveIntegerField(verbose_name='priceoftheservice')),
            ],
        ),
        migrations.CreateModel(
            name='Users',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('login', models.CharField(max_length=50, verbose_name='login')),
                ('name', models.CharField(max_length=50, verbose_name='name')),
                ('password', models.CharField(max_length=50, verbose_name='password')),
                ('IsAdmin', models.BinaryField(verbose_name='IsAdmin')),
            ],
        ),
        migrations.AlterField(
            model_name='booking',
            name='accountnumber',
            field=models.PositiveIntegerField(verbose_name='account number'),
        ),
        migrations.AlterField(
            model_name='booking',
            name='dateofbooking',
            field=models.DateTimeField(verbose_name='date of booking'),
        ),
    ]
